### PR TITLE
move stdio higher to fix build on rhat linux jpeg issue

### PR DESCRIPTION
**Pull request by smokinguns**
Ran into an issue where FILE type was not known, so I move stdio.h to be higher than jpeglib.h and it seems to resolve the issue. This worked on macos as well.

In file included from c_src/Tensorflex.c:4:0:
/usr/include/jpeglib.h:1000:30: error: unknown type name ‘FILE’
 EXTERN(void) jpeg_stdio_dest JPP((j_compress_ptr cinfo, FILE * outfile));
                              ^
/usr/include/jpeglib.h:1001:29: error: unknown type name ‘FILE’
 EXTERN(void) jpeg_stdio_src JPP((j_decompress_ptr cinfo, FILE * infile));

### CODE REVIEW

**Comment by anshuman23** [comment]
Thanks Bradley, I am merging it now :)

**Comment by smokinguns** [comment]
@anshuman23 Can you explain? It looks like you reverted the move of stdio.h, I'm not really concerned about anything else. The print statements were to clean up the warnings.  The placement of of stdio.h below jpeglib.h causes the previously mentioned errors in the original pull request.

**Comment by anshuman23** [comment]
Yeah so Travis wasn't building for some reason on master. I'm going to figure out why, and then merge. Don't worry, should be done soon. Can you use a local clone of the repo with the changes till then?

**Comment by smokinguns** [comment]
@anshuman23 sounds good. I had the same problem with travis. I originally thought it had to do with the warnings, but when I got the 3rd one to build without changing anything significant, I started to suspect the problem might just be with travis.

**Pull request merged**
